profile: change the select_timeout to 500ms (from 10ms)
When the link is fairly quiet (stream_rate of 1), this saves substantial CPU
 - about 35%.  I see no downside other than the idle_hooks will be getting
called less often when we haven't received a packet.  This seems harmless
because as long as we receive any packet we will walk through all the
idle hooks.

@tridge, do you have an opinion on this?  The cmd line I used to test this
with a pixhawk on serial is:

kevinh@kevin-think:~/development/drone/MAVProxy/MAVProxy/modules$ mavproxy.py --master=/dev/ttyUSB0,921600 --daemon --rtscts --streamrate=4 --nolog --max-packets=5000
FIXME - using native code - remove this string
Running script /home/kevinh/.mavinit.scr
-> set moddebug 2
-> module load droneapi.module.api
Traceback (most recent call last):
  File "/home/kevinh/development/drone/MAVProxy/MAVProxy/mavproxy.py", line 260, in load_module
    m = import_package(modpath)
  File "/home/kevinh/development/drone/MAVProxy/MAVProxy/mavproxy.py", line 390, in import_package
    mod = __import__(name)
ImportError: No module named mavproxy_droneapi.module.api

DroneAPI loaded
Loaded module droneapi.module.api
-> module unload terrain
Unloaded module terrain
-> module unload log
Unloaded module log
-> module unload battery
Unloaded module battery
-> module unload fence
Unloaded module fence
-> module unload rally
Unloaded module rally
-> module unload calibration
Unloaded module calibration
-> module unload relay
Unloaded module relay
-> module unload misc
Unloaded module misc
-> module unload rc
Unloaded module rc
-> module load profile
NOW PROFILING...
Loaded module profile
RTL> Mode RTL
height 20
APM: ArduPlane V3.2.1beta1 (5d8cec23)
APM: PX4: a55016a5 NuttX: 29c0c2d1
APM: PX4v2 00270030 31334705 39343031
Received 501 parameters
Received 5001 packets, exiting.
Unloading module link
Unloading module wp
Unloading module param
Unloading module tuneopt
Unloading module arm
Unloading module mode
Unloading module auxopt
Unloading module cmdlong
Unloading module output
Unloading module api
Unloading module profile
Profile results:

Clock type: CPU
Ordered by: totaltime, desc

name                                  ncall  tsub      ttot      tavg
..hon2.7/threading.py:752 Thread.run  1      0.000020  2.451667  2.451667
..MAVProxy/mavproxy.py:670 main_loop  1      0.119878  2.451648  2.451648
..oxy/mavproxy.py:469 process_master  2621   0.098110  1.674446  0.000639
..tmega.py:4858 MAVLink.parse_buffer  2621   0.026367  1.343777  0.000513
..lotmega.py:4802 MAVLink.parse_char  7623   0.094926  1.314783  0.000172
..otmega.py:4797 MAVLink.__callbacks  5001   0.024168  1.003452  0.000201
...py:230 LinkModule.master_callback  5001   0.209326  0.979283  0.000196
..ink.py:409 LinkModule.__to_modules  5001   0.165348  0.505368  0.000101
..oxy/mavproxy.py:635 periodic_tasks  2622   0.142833  0.474579  0.000181
..link/mavutil.py:723 mavserial.recv  2623   0.020489  0.207706  0.000079
..ial/serialposix.py:453 Serial.read  2623   0.094445  0.187218  0.000071
..y:4792 MAVLink.__parse_char_native  7623   0.025134  0.182328  0.000024
../mp_module.py:83 LinkModule.master  7967   0.019734  0.179809  0.000023
..oxy/mavproxy.py:188 MPState.master  7967   0.121668  0.160075  0.000020
...py:228 ParamModule.mavlink_packet  5001   0.025428  0.156412  0.000031
..util.py:209 mavserial.post_message  10002  0.121470  0.150073  0.000015
..param.py:232 ParamModule.idle_task  2622   0.026566  0.110682  0.000042
..pi.py:396 APIModule.mavlink_packet  5001   0.047969  0.092042  0.000018
..ings.py:104 MPSettings.__getattr__  47760  0.068374  0.068374  0.000001
..til.py:1055 periodic_event.trigger  13111  0.045949  0.056838  0.000004
..y/mavproxy.py:597 set_stream_rates  2623   0.034757  0.051424  0.000020
..MAVLink_heartbeat_message.__init__  5060   0.034556  0.049914  0.000010
..proxy_wp.py:105 WPModule.idle_task  2622   0.017028  0.043946  0.000017
../python2.7/Queue.py:93 Queue.empty  2622   0.023741  0.040955  0.000016
..k.py:292 LinkModule.__update_state  5001   0.016481  0.035714  0.000007
../mp_module.py:43 LinkModule.module  7866   0.017960  0.027715  0.000004
..MAVLink_heartbeat_message.get_type  36403  0.027133  0.027133  0.000001
../mp_module.py:51 LinkModule.status  31566  0.025399  0.025399  0.000001
..oxy/mavproxy.py:626 send_heartbeat  54     0.000704  0.023306  0.000432
..ega.py:6039 MAVLink.heartbeat_send  54     0.000644  0.022440  0.000416
..le.py:36 LinkModule.mavlink_packet  40008  0.022424  0.022424  0.000001
..xy_link.py:49 LinkModule.idle_task  2622   0.009670  0.021997  0.000008
..3 ParamState.handle_mavlink_packet  5001   0.016040  0.020191  0.000004
..param.py:43 ParamState.fetch_check  2622   0.008718  0.019536  0.000007
..y_wp.py:55 WPModule.mavlink_packet  5001   0.015795  0.019340  0.000004
..e/api.py:383 APIModule.__on_change  1142   0.008684  0.016335  0.000014
..mega.py:41 MAVLink_header.__init__  5178   0.015576  0.015576  0.000003
...py:211 LinkModule.report_altitude  221    0.007198  0.015535  0.000070
..5 LinkModule.handle_msec_timestamp  1337   0.011396  0.014437  0.000011
..339 MAVLink_heartbeat_message.pack  108    0.001080  0.014306  0.000132
..112 MAVLink_heartbeat_message.pack  118    0.003181  0.013920  0.000118
..ardupilotmega.py:4771 MAVLink.send  59     0.001256  0.011933  0.000202
..dule.py:26 TuneoptModule.idle_task  20976  0.011921  0.011921  0.000001
..a.py:6019 MAVLink.heartbeat_encode  54     0.000582  0.010967  0.000203
..oxy/mavproxy.py:182 MPState.module  7866   0.009755  0.009755  0.000001
..ython2.7/Queue.py:200 Queue._qsize  2622   0.006221  0.008935  0.000003
..mavcrc.py:23 x25crc.accumulate_str  236    0.004502  0.008283  0.000035
...py:179 MPVehicle.notify_observers  1876   0.005768  0.007652  0.000004
..erator/mavcrc.py:6 x25crc.__init__  118    0.000833  0.006997  0.000059
..pi.py:457 APIModule.send_to_server  5001   0.005434  0.005434  0.000001
..y:85 MAVLink_message.get_srcSystem  5214   0.005132  0.005132  0.000001
..mega.py:91 MAVLink_message.get_seq  5001   0.005008  0.005008  0.000001
..8 MAVLink_message.get_srcComponent  5214   0.004480  0.004480  0.000001
..ink/mavutil.py:733 mavserial.write  59     0.000337  0.004265  0.000072
..al/serialposix.py:488 Serial.write  59     0.001353  0.003928  0.000067
..ule.py:67 ParamModule.vehicle_name  2622   0.003790  0.003790  0.000001
..hon/droneapi/module/api.py:432 set  1776   0.003331  0.003331  0.000002
..tor/mavcrc.py:14 x25crc.accumulate  236    0.003286  0.003286  0.000014
..4 MAVLink.request_data_stream_send  4      0.000057  0.001549  0.000387
..MAVLink_heartbeat_message.__init__  54     0.000659  0.001387  0.000026
..k_request_data_stream_message.pack  8      0.000076  0.001002  0.000125
..il.py:344 mavserial.wait_heartbeat  1      0.000011  0.000962  0.000962